name: Build and push add-on images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64 image and push
        uses: docker/build-push-action@v4
        with:
          context: ./dendrite
          file: ./dendrite/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest
          tags: |
            ghcr.io/vgark/ha-addons-dendrite/dendrite-amd64:latest

  build-arm64:
    runs-on: ubuntu-latest
    needs: build-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build arm64 image and push
        uses: docker/build-push-action@v4
        with:
          context: ./dendrite
          file: ./dendrite/Dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/arm64-base:latest
          tags: |
            ghcr.io/vgark/ha-addons-dendrite/dendrite-arm64:latest
